exports.tokensNames = {
  REFRESH: 'REFRESH_TOKEN',
  ACCESS: 'ACCESS_TOKEN',
  RESTORE: 'RESTORE_TOKEN',
};

exports.tokensDevKeys = {
  REFRESH: 'REFRESH_TOKEN_KEY',
  ACCESS: 'ACCESS_TOKEN_KEY',
  RESTORE: 'RESTORE_TOKEN_KEY',
};
