export const commonFetchStatuses = {
  FAILED: 'FAILED',
  IDLE: 'IDLE',
  LOADING: 'LOADING',
  SUCCEEDED: 'SUCCEEDED',
};

export const tokensNames = {
  ACCESS_TOKEN_HEADERS_NAME: 'access-token',
  ACCESS_TOKEN_STORAGE_NAME: 'accessToken',
  REFRESH_TOKEN_HEADERS_NAME: 'refresh-token',
  REFRESH_TOKEN_STORAGE_NAME: 'refreshToken',
};

export const delays = {
  AFTER_SIGN_IN: 1000,
  BEFORE_HIDE_ERROR_SNACKBAR: 10000,
  BEFORE_HIDE_SUCCESS_SNACKBAR: 2000,
  BEFORE_HIDE_WARNING_SNACKBAR: 10000,
  BEFORE_HIDE_WARNING_SNACKBAR: 10000,
  BEFORE_REDIRECT_FROM_DONE: 3000,
  BETWEEN_STEPS: 1200,
};

export const fetchErrorsNames = {
  SIGN_OUT_FROM_ANOTHER_DEVICE: 'SIGN_OUT_FROM_ANOTHER_DEVICE',
  PASSWORDS_ARE_EQUAL: 'PASSWORDS_ARE_EQUAL',
  ACCESS_DENIED: 'ACCESS_DENIED',
  EXPIRED_CONFIRMATION_CODE: 'EXPIRED_CONFIRMATION_CODE',
  EXPIRED_RESTORE_PASSWORD_SESSION: 'EXPIRED_RESTORE_PASSWORD_SESSION',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  INCORRECT_AUTH_DATA: 'INCORRECT_AUTH_DATA',
  INCORRECT_CONFIRMATION_CODE: 'INCORRECT_CONFIRMATION_CODE',
  INCORRECT_OLD_PASSWORD: 'INCORRECT_OLD_PASSWORD',
  INVALID_DATA: 'INVALID_DATA',
  INVALID_TOKEN: 'INVALID_TOKEN',
  LOGIN_ALREADY_USE: 'LOGIN_ALREADY_USE',
  MAIL_PROVIDER_ERROR: 'MAIL_PROVIDER_ERROR',
  MISSING_TOKEN: 'MISSING_TOKEN',
  USER_BY_EMAIL_NOT_FOUND: 'USER_BY_EMAIL_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  DOUBLE_AUTHENTICATED_DENIED: 'DOUBLE_AUTHENTICATED_DENIED',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
};
