export const authFetchStatusNames = {
  CREATE_NEW_PASSWORD: 'createNewPassword',
  GET_REST_PASSWORD_CREDENTIALS: 'getRestPasswordCredentials',
  RESEND_REST_PASSWORD_CREDENTIALS: 'resendRestPasswordCredentials',
  SIGN_IN: 'sighIn',
  SIGN_UP: 'signUp',
  VERIFY_REST_REST_PASSWORD_CONFIRM_CODE: 'verifyRestPasswordConfirmCode',
};

export const fetchErrorsNames = {
  ACCESS_DENIED: 'ACCESS_DENIED',
  DOUBLE_AUTHENTICATED_DENIED: 'DOUBLE_AUTHENTICATED_DENIED',
  EXPIRED_CONFIRMATION_CODE: 'EXPIRED_CONFIRMATION_CODE',
  EXPIRED_RESTORE_PASSWORD_SESSION: 'EXPIRED_RESTORE_PASSWORD_SESSION',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  INCORRECT_AUTH_DATA: 'INCORRECT_AUTH_DATA',
  INCORRECT_CONFIRMATION_CODE: 'INCORRECT_CONFIRMATION_CODE',
  INCORRECT_OLD_PASSWORD: 'INCORRECT_OLD_PASSWORD',
  INVALID_DATA: 'INVALID_DATA',
  INVALID_TOKEN: 'INVALID_TOKEN',
  LOGIN_ALREADY_USE: 'LOGIN_ALREADY_USE',
  MAIL_PROVIDER_ERROR: 'MAIL_PROVIDER_ERROR',
  MISSING_TOKEN: 'MISSING_TOKEN',
  PASSWORDS_ARE_EQUAL: 'PASSWORDS_ARE_EQUAL',
  USER_BY_EMAIL_NOT_FOUND: 'USER_BY_EMAIL_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
};
