export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const ENTITY_FAILURE = 'ENTITY_FAILURE';
export const ENTITY_CREATE = 'ENTITY_CREATE';
export const ENTITY_UPDATE = 'ENTITY_UPDATE';
export const ENTITY_FETCH = 'ENTITY_FETCH';
export const ENTITY_DELETE = 'ENTITY_DELETE';
export const SELECT_ENTITY_ITEM = 'SELECT_ENTITY_ITEM';
export const CLEAR_ENTITY_LIST = 'CLEAR_ENTITY_LIST';

export const SET_CARD = 'SET_CARD';
export const SET_NEW_CARD = 'SET_NEW_CARD';
export const DELETE_CARD = 'DELETE_CARD';

export const SET_MONOBANK_ACCOUT = 'SET_MONOBANK_ACCOUT';
export const SET_NEW_MONOBANK_ACCOUNT = 'SET_NEW_MONOBANK_ACCOUNT';
export const ADD_DATA_TO_STATEMENTS = 'ADD_DATA_TO_STATEMENTS';
export const SET_USER_MONOBANK_ACCOUNTS = 'SET_USER_MONOBANK_ACCOUNTS';
export const SET_STATEMENT_DATA = 'SET_STATEMENT_DATA';
export const REMOVE_MONOBANK_TRANSACTION = 'REMOVE_MONOBANK_TRANSACTION';
