export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const GET_CARDS_SUCCESS = 'dashboard/GET_CARDS_SUCCESS';
export const GET_TRANSACTIONS_SUCCESS = 'dashboard/GET_TRANSACTIONS_SUCCESS';
export const GET_SUMMARY_SUCCESS = 'dashboard/GET_SUMMARY_SUCCESS';
export const SET_LOADING_STATUS = 'dashboard/SET_LOADING_STATUS';

export const ENTITY_UPDATE = 'ENTITY_UPDATE';
export const ENTITY_FETCH = 'ENTITY_FETCH';
export const ENTITY_DELETE = 'ENTITY_DELETE';
export const SELECT_ENTITY_ITEM = 'SELECT_ENTITY_ITEM';
export const CLEAR_ENTITY_LIST = 'CLEAR_ENTITY_LIST';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_NEW_CATEGORY_DATA = 'SET_NEW_CATEGORY_DATA';
export const CLEAR_NEW_CATEGORY_DATA = 'CLEAR_NEW_CATEGORY_DATA';
