export const UPDATE_PRIVATE_FETCH_STATUS = 'common/UPDATE_PRIVATE_FETCH_STATUS';
export const UPDATE_COMMON_FETCH_STATUS = 'common/UPDATE_COMMON_FETCH_STATUS';
export const SET_FETCH_ERROR = 'common/SET_FETCH_ERROR';
