export const RECEIVE_ACCOUNT_SETTINGS = 'settings/RECEIVE_ACCOUNT_SETTINGS';
export const UPDATE_SECURITY_SETTINGS = 'settings/UPDATE_SECURITY_SETTINGS';
export const UPDATE_PASSWORD = 'settings/UPDATE_PASSWORD';
